### ISSUE TITLE
Update Humanizer reference to Humanizer.Core

### ISSUE THREAD

**Issue by sgwatgit** [gavynriebau/Dates.Recurring#1]
[Humanizer](https://github.com/Humanizr/Humanizer) updated their repository and released version 2.0 which restructured their project. Humanizer.Core now suffices as a library for your project and doesn't include [all of the localization .dlls](https://github.com/Humanizr/Humanizer/issues/59).

I can make a pull request to update this project to reference the updated Humanizr nuget package if you would be willing to update your Nuget package.

Thanks!

Edit --

Here is my pull request https://github.com/gavynriebau/Dates.Recurring/pull/2

**Comment by gavynriebau** [comment]
Pull request has now been merged
