### ISSUE TITLE
First date of an every saturday schedule returns different date

### ISSUE THREAD

**Issue by Jogai** [gavynriebau/Dates.Recurring#13]
This test (I made) fails, but should pass I think

        [Fact]
        public void Daily_Every_Saturday_First()
        {
            // Arrange.
            IRecurring daily = Recurs
                .Starting(new DateTime(2019, 1, 16)) //Starting on a wednesday
                .Every(1)
                .Days()
                .Including(Day.SATURDAY) //Only on saturdays
                .Ending(new DateTime(2019, 5, 15))
                .Build();

            // Act.
            List<DateTime> dates = new List<DateTime>();

            DateTime? date = new DateTime(2019, 1, 1); //Date earlier, could be from somewhere else
            while (date.HasValue)
            {
                date = daily.Next(date.Value);
                if (!date.HasValue)
                {
                    break;
                }

                dates.Add(date.Value);
            }

            Assert.Equal(new DateTime(2019, 1, 19), dates.First()); //First occurrence in a every saturday schedule should be a saturday
        }

**Comment by zachglontz** [comment]
I personally like that it includes the Wednesday date. If I'm creating a new recurring event for a customer, they might want services on Saturday, but we can go ahead and start their first service on Wednesday. I've come across this scenario many times in my business.

**Comment by Jogai** [comment]
I needed something that was compatible with http://jakubroztocil.github.io/rrule/. In the end I created my own library
