### ISSUE TITLE
Can we have a NET Core version?

### ISSUE THREAD

**Issue by nikkilocke** [gavynriebau/Dates.Recurring#18]
If I made a NET Core version, would you be happy for a pull request, to make a NET Core branch?

**Comment by nikkilocke** [comment]
Have compiled the main code with NET Core (no changes, other than a new project file), but don't know how to get the tests to run. Any ideas?

**Comment by nikkilocke** [comment]
Have done a pull request. Only needed to add NET Core solution and project files - all source files completely unchanged. Building NET Core version creates nuget file automatically.

**Comment by gavynriebau** [comment]
Thanks @nikkilocke 
I've updated the Dates.Recurring.csproj file and set the "TargetFrameworks" attribute to "netstandard2.1;netcoreapp2.0" following the advice in this documentation:
https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file

You should now be able to install and use the latest Dates.Recurring nuget package version 2.0.10
