### ISSUE TITLE
Get a list of dates

### ISSUE THREAD

**Issue by Jogai** [gavynriebau/Dates.Recurring#4]
I dont know if I'm missing something, but if I want to have a list of dates from a pattern I do this:

```c#
        public List<DateTime> DatesRecurringListContains()
        {
            var r = Recurs
                .Starting(new DateTime(2017, 1, 1))
                .Every(2)
                .Days()
                .Ending(new DateTime(2017, 4, 30))
                .Build();

            var f = r.Next(new DateTime(2017, 1, 1).AddDays(-1));
            if (f.HasValue)
            {
                var rl = new List<DateTime> { f.Value };
                while (f != null)
                {
                    f = r.Next(f.Value);
                    if (f != null) rl.Add(f.Value);
                }

                if (r.Next(new DateTime(2017, 4, 28)) == new DateTime(2017, 4, 29))
                {
                    return rl;
                }
            }
            return null;
        }
```
But this is bad for performance, compared to some alternatives:

```ini

Host Process Environment Information:
BenchmarkDotNet.Core=v0.9.9.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i5-4590 CPU 3.30GHz, ProcessorCount=4
Frequency=3215221 ticks, Resolution=311.0206 ns, Timer=TSC
CLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
GC=Concurrent Workstation
JitModules=clrjit-v4.6.1080.0

Type=Benches  Mode=Throughput  

```
                     Method |      Median |    StdDev |
--------------------------- |------------ |---------- |
 DatesRecurringListContains | 159.6398 us | 1.2346 us |
       DarecaliListContains |   3.0112 us | 0.1232 us |

Is there a smarter way to get a list of the recurring dates?

**Comment by gavynriebau** [comment]
@Jogai update to version 1.0.14 and re-test, I've added a change which will improve performance.

**Comment by Jogai** [comment]
Wow! Stunned by the fact that you fixed it already.

Still the difference is fairly big:

                     Method |     Median |    StdDev |
--------------------------- |----------- |---------- |
 DatesRecurringListContains | 55.3202 us | 0.7109 us |
       DarecaliListContains |  2.9070 us | 0.0476 us |

**Comment by gavynriebau** [comment]
You're welcome to add a pull request if you know a way to improve the performance further otherwise you may need to use Darecali or your own implementation if you require a very high level of performance.
